---
title: "Leslie Matrix Example"
author: "Halina Do-Linh"
date: "8/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Creating Matrices in R
*Use the `matrix()` function to wrap a series of values (a vector) into a matrix.*

- Use `nrow =` to specify number of rows.
- Use `ncol =` to specify number of columns.
- Use `byrow = TRUE` to populate the matrix by ROWS instead of columns (default is columns).

### Making a sequence of values

```{r}

cats <- c(1, 9, 5, 3, 12, 10, 7, 100)

# Wrap cats into a matrix

cats_matrix <- matrix(data = cats, nrow = 4, ncol = 5, byrow = TRUE)

# Warning that appears is not an error, just a friendly heads up

```

```{r}

dogs <- matrix(data = c(0, 1, 2, 3), nrow = 2, ncol = 2, byrow = TRUE)

tacos <- matrix(data = c(3, 4, 10, 12), nrow = 2, ncol = 2, byrow = 2)

dogs + tacos

tacos - dogs

4 * dogs

dogs %*% tacos

# Remember %*% is dot product! 

```

## Time to make a Leslie Matrix

```{r}

insect_leslie <- matrix(data = c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0.6), nrow = 3, ncol = 3, byrow = TRUE)

# Specify the initial conditions. What is the population at each life stage at year 0?

insect_y0 <- c(12000, 700, 500)

# Time to do dot product - Project population in each life stage for year 1

insect_y1 <- insect_leslie %*% insect_y0

insect_y1

# Project the population at each life stage for years 2, 3, and 4

insect_y2 <- insect_leslie %*% insect_y1

insect_y3 <- insect_leslie %*% insect_y2

insect_y4 <- insect_leslie %*% insect_y3

```


